// This file is auto-generated by TanStack Router.
// Do not edit manually. Run `pnpm dev` or `pnpm build` to regenerate.
// @ts-nocheck

import { RootRoute } from "@tanstack/react-router";

export interface FileRoutesByPath {}

export const routeTree = {} as unknown as RootRoute;
